# Generated by Django 3.0.6 on 2020-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200618_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tag',
        ),
        migrations.AddField(
            model_name='photo',
            name='Cate',
            field=models.CharField(default='wedding', max_length=20),
        ),
    ]
