# Generated by Django 3.0.6 on 2020-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200623_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Cate',
        ),
        migrations.AddField(
            model_name='photo',
            name='cf',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='cp',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='cw',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
