# Generated by Django 3.0.6 on 2020-06-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200625_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='cw',
            new_name='alt',
        ),
    ]
