# Generated by Django 3.0.6 on 2020-06-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
