# Generated by Django 3.0.6 on 2020-06-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20200626_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='Contact',
        ),
    ]
