# Generated by Django 3.0.6 on 2020-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20200626_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
