# Generated by Django 3.0.6 on 2020-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20200626_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('writter', models.CharField(max_length=50)),
                ('article', models.CharField(default='None', max_length=10000)),
            ],
        ),
    ]
