# Generated by Django 3.0.6 on 2020-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=10000),
        ),
    ]
