# Generated by Django 3.0.6 on 2020-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20200627_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.IntegerField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
