# Generated by Django 3.0.6 on 2020-06-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20200627_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
