# Generated by Django 3.0.6 on 2020-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alt',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
