# Generated by Django 3.0.6 on 2020-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_article_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Describe your keypoint of the article in between 200 words', max_length=250),
        ),
    ]
