# Generated by Django 3.0.6 on 2020-06-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
