# Generated by Django 3.0.6 on 2020-06-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_auto_20200627_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ['-pk']},
        ),
    ]
