# Generated by Django 3.0.6 on 2020-06-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_auto_20200629_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
