# Generated by Django 3.0.6 on 2020-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0023_auto_20200629_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='head3',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='article',
            name='bio',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='head1',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='head2',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
