# Generated by Django 3.0.6 on 2020-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0024_auto_20200629_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avater',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='head1',
            field=models.TextField(default='', max_length=500),
        ),
    ]
