# Generated by Django 3.0.6 on 2020-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0025_auto_20200629_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bio',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='head1',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='head3',
            field=models.TextField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
